const Project = require('../models/Project');

const projectsData = [
  // ALGERIA
  {
    slug: "gcb-desalination",
    country: "Algeria",
    countryCode: "DZ",
    title_en: "GCB – National Company for Civil Engineering and Construction",
    title_ar: "الشركة الوطنية للهندسة المدنية والبناء",
    subtitle: "Seawater Desalination Plants",
    sector: "Infrastructure",
    client_en: "GCB",
    client_ar: "GCB",
    location_en: "Eastern, Western, and Central Algeria",
    location_ar: "شرق وغرب ووسط الجزائر",
    description_en: "Multiple seawater desalination plant projects executed in collaboration with local contractors, utilizing advanced concrete protection and waterproofing solutions.",
    description_ar: "مشاريع متعددة لمحطات تحلية مياه البحر تم تنفيذها بالتعاون مع مقاولين محليين، باستخدام حلول متقدمة لحماية الخرسانة والعزل المائي.",
    products: ["EUNIFLOW 110", "EUNICURE CUREX", "EUNIMAR DELTRAPO"],
    image_url: "https://images.unsplash.com/photo-1581094271901-8022df4466f9?q=80&w=800&auto=format&fit=crop",
  },
  {
    slug: "cosider-silos",
    country: "Algeria",
    countryCode: "DZ",
    title_en: "Industrial Facilities & Grain Silos",
    title_ar: "المرافق الصناعية وصوامع الحبوب",
    subtitle: "COSIDER",
    sector: "Industrial",
    client_en: "COSIDER",
    client_ar: "كوسيدار",
    location_en: "Adrar, M'Sila, and other provinces",
    location_ar: "أدرار، المسيلة ومقاطعات أخرى",
    description_en: "Strategic projects supporting Algeria's national goal of achieving self-sufficiency in wheat production and reducing imports.",
    description_ar: "مشاريع استراتيجية تدعم هدف الجزائر الوطني في تحقيق الاكتفاء الذاتي من إنتاج القمح وتقليل الواردات.",
    products: ["EUNIFLOW 110", "EUNICURE CUREX", "EUNIMAR DELTRAPO"],
    image_url: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=800&auto=format&fit=crop",
  },
  {
    slug: "inerkib-power",
    country: "Algeria",
    countryCode: "DZ",
    title_en: "Power Generation Plants",
    title_ar: "محطات توليد الطاقة",
    subtitle: "INERKIB (formerly INERGA)",
    sector: "Power & Energy",
    client_en: "INERKIB with Samsung and Hyundai",
    client_ar: "إينركيب مع سامسونج وهيونداي",
    location_en: "Boumerdès, Mostaganem, Jijel, Setif, Naama, Biskra, Khenchela",
    location_ar: "بومرداس، مستغانم، جيجل، سطيف، النعامة، بسكرة، خنشلة",
    description_en: "Multiple high-capacity power generation plant projects executed under a five-year supply contract.",
    description_ar: "مشاريع متعددة لمحطات توليد الطاقة عالية القدرة تم تنفيذها بموجب عقد توريد مدته خمس سنوات.",
    products: ["EUNIFLOW 110", "EUNITARD P2", "EUNICURE CUREX", "EUNIMAR DELTRAPO", "EURIPAR BA9", "EUNICOTE ES9", "EUNICOTE MRA1", "Cemfiber 12 mm"],
    image_url: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?q=80&w=800&auto=format&fit=crop",
  },
  {
    slug: "metro-m28",
    country: "Algeria",
    countryCode: "DZ",
    title_en: "Metro M28 Project – Algiers",
    title_ar: "مشروع مترو الجزائر M28",
    subtitle: "Algiers Metro Expansion",
    sector: "Infrastructure",
    client_en: "COSIDER",
    client_ar: "كوسيدار",
    location_en: "Algiers",
    location_ar: "الجزائر",
    description_en: "Key part of expanding the capital's metro network with locally manufactured materials developed in line with European standards.",
    description_ar: "جزء رئيسي من توسيع شبكة مترو العاصمة بمواد مصنعة محلياً مطورة وفق المعايير الأوروبية.",
    products: ["EUNIFLOW 110", "EUNISET GA4", "EURIPAR BA9", "CEMFIBER 12 mm"],
    image_url: "https://images.unsplash.com/photo-1474487548417-781cb71495f3?q=80&w=800&auto=format&fit=crop",
  },

  // LEBANON
  {
    slug: "souk-beirut",
    country: "Lebanon",
    countryCode: "LB",
    title_en: "Souk Beirut",
    title_ar: "أسواق بيروت",
    subtitle: "Commercial Development",
    sector: "Commercial",
    client_en: "Hourie",
    client_ar: "حوري",
    location_en: "Beirut, Lebanon",
    location_ar: "بيروت، لبنان",
    description_en: "Major commercial development utilizing advanced concrete and waterproofing solutions for long-term durability.",
    description_ar: "مشروع تجاري رئيسي يستخدم حلول الخرسانة والعزل المائي المتقدمة من أجل الاستدامة طويلة الأمد.",
    products: ["EUNICEM", "EURIPARE", "EUNITARD"],
    image_url: "https://images.unsplash.com/photo-1555636222-cae831e670b3?q=80&w=800&auto=format&fit=crop",
  },
  {
    slug: "sama-beirut",
    country: "Lebanon",
    countryCode: "LB",
    title_en: "Sama Beirut",
    title_ar: "سما بيروت",
    subtitle: "Residential Towers",
    sector: "High Rise",
    client_en: "Man Enterprise",
    client_ar: "مان انتربرايز",
    location_en: "Achrafieh, Lebanon",
    location_ar: "الأشرفية، لبنان",
    description_en: "High-rise residential towers project with high-performance concrete and protective systems.",
    description_ar: "مشروع أبراج سكنية شاهقة مع خرسانة عالية الأداء وأنظمة حماية.",
    products: ["EUNICEM", "EURIPARE", "EUNICOTE"],
    image_url: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=800&auto=format&fit=crop",
  },
  {
    slug: "four-seasons-beirut",
    country: "Lebanon",
    countryCode: "LB",
    title_en: "Four Seasons Hotel",
    title_ar: "فندق الفورسيزونز",
    subtitle: "Premium Hospitality",
    sector: "Hospitality",
    client_en: "Man-Sursock",
    client_ar: "مان-سرسق",
    location_en: "Beirut, Lebanon",
    location_ar: "بيروت، لبنان",
    description_en: "Specialized works for premium hospitality development with high-quality concrete admixtures and protective systems.",
    description_ar: "أعمال متخصصة لمشروع ضيافة راقي مع إضافات خرسانية عالية الجودة وأنظمة حماية.",
    products: ["EUNICEM", "EUNIPARE", "EUNIGROUT"],
    image_url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop",
  },
  {
    slug: "aj-wadi",
    country: "Lebanon",
    countryCode: "LB",
    title_en: "AJ Wadi Residence",
    title_ar: "مشروع وادي إيه جيه السكني",
    subtitle: "High-End Residential",
    sector: "High Rise",
    client_en: "Man Enterprise",
    client_ar: "مان انتربرايز",
    location_en: "Solidere, Beirut, Lebanon",
    location_ar: "سوليدير، بيروت، لبنان",
    description_en: "High-end residential development with specialized concrete and protective solutions for long-term durability.",
    description_ar: "مشروع سكني راقي مع حلول خرسانية وحماية متخصصة للاستدامة.",
    products: ["EUNICEM", "EURIPARE", "EUNICOTE"],
    image_url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=800&auto=format&fit=crop",
  },

  // JORDAN
  {
    slug: "munition-storage",
    country: "Jordan",
    countryCode: "JO",
    title_en: "Munition Storage Area – US Corps",
    title_ar: "منطقة تخزين الذخيرة - فيلق الولايات المتحدة",
    subtitle: "Military Infrastructure",
    sector: "Infrastructure",
    client_en: "American International Contractors, Inc. (AICI)",
    client_ar: "المقاولون الدوليون الأمريكيون",
    location_en: "Jordan",
    location_ar: "الأردن",
    description_en: "Critical munition storage facility with advanced waterproofing and protective systems meeting stringent requirements.",
    description_ar: "منشأة تخزين ذخيرة حيوية مع أنظمة عزل مائي وحماية متقدمة تلبي متطلبات صارمة.",
    products: ["TOPSEAL 200", "EUNICOTE BE", "EUNISEAL PARASEAL", "EUNISEAL VERTISEAL", "EUNICOTE ZNR", "ECA Waterplug+"],
    image_url: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=800&auto=format&fit=crop",
  },
  {
    slug: "sjfmei-healthcare",
    country: "Jordan",
    countryCode: "JO",
    title_en: "SJFMEI Healthcare & Education Project",
    title_ar: "مشروع الرعاية الصحية والتعليم SJFMEI",
    subtitle: "Healthcare & Education",
    sector: "Healthcare",
    client_en: "Hussein Atieh & Sons Co.",
    client_ar: "شركة حسين عطية وأولاده",
    location_en: "Jordan",
    location_ar: "الأردن",
    description_en: "Comprehensive healthcare and education facility with reliable waterproofing and joint sealing solutions.",
    description_ar: "مرفق شامل للرعاية الصحية والتعليم مع حلول موثوقة للعزل المائي وختم الوصلات.",
    products: ["EUNICOTE BE", "EUNICOTE RBE", "ECA WaterStop", "ECA Cartonal", "EUNICOTE MRAI", "ECA Polyethylene Sheet", "ECA Swellable WaterStop"],
    image_url: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=800&auto=format&fit=crop",
  },
  {
    slug: "jordan-ahli-bank",
    country: "Jordan",
    countryCode: "JO",
    title_en: "Jordan Ahli Bank – New Headquarters",
    title_ar: "البنك الأهلي الأردني – المقر الرئيسي الجديد",
    subtitle: "Banking Headquarters",
    sector: "Commercial",
    client_en: "MID Contracting Company",
    client_ar: "شركة ميد للمقاولات",
    location_en: "Jordan",
    location_ar: "الأردن",
    description_en: "Flagship banking development with advanced waterproofing and joint sealing systems for long-term performance.",
    description_ar: "مشروع مصرفي رائد مع أنظمة عزل مائي وختم وصلات متقدمة لأداء طويل الأمد.",
    products: ["EUNICOTE BE", "PREMIERFLEX 2000", "EUNISEAL PU Sealant"],
    image_url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=800&auto=format&fit=crop",
  },

  // IRAQ
  {
    slug: "central-bank-iraq",
    country: "Iraq",
    countryCode: "IQ",
    title_en: "Central Bank of Iraq",
    title_ar: "البنك المركزي العراقي",
    subtitle: "National Banking Infrastructure",
    sector: "Commercial",
    client_en: "Central Bank of Iraq",
    client_ar: "البنك المركزي العراقي",
    location_en: "Baghdad, Iraq",
    location_ar: "بغداد، العراق",
    description_en: "Nationally significant development supporting the stability and growth of the Iraqi economy with advanced construction solutions.",
    description_ar: "مشروع وطني هام يدعم استقرار ونمو الاقتصاد العراقي من خلال حلول بناء متقدمة.",
    products: ["DCIS", "Microsilica", "ADProfe 75ME", "EUNIFLOW 612i"],
    image_url: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?q=80&w=800&auto=format&fit=crop",
  },
  {
    slug: "movenpick-baghdad",
    country: "Iraq",
    countryCode: "IQ",
    title_en: "Mövenpick Hotel",
    title_ar: "فندق موڤنبيك",
    subtitle: "Premium Hospitality",
    sector: "Hospitality",
    client_en: "Mövenpick Hotels & Resorts",
    client_ar: "فنادق ومنتجعات موڤنبيك",
    location_en: "Baghdad, Iraq",
    location_ar: "بغداد، العراق",
    description_en: "High-profile hospitality development with comprehensive waterproofing for 400 hotel bathrooms and extensive steel corrosion treatment.",
    description_ar: "مشروع ضيافة بارز يتضمن عزلاً مائياً شاملاً لـ 400 حمام ومعالجة مكثفة لصدأ الحديد.",
    products: ["ECA Waterproofing Systems", "Corrosion Protection"],
    image_url: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?q=80&w=800&auto=format&fit=crop",
  },
  {
    slug: "rixos-baghdad",
    country: "Iraq",
    countryCode: "IQ",
    title_en: "Rixos Hotel",
    title_ar: "فندق ريكسوس",
    subtitle: "Luxury Hospitality",
    sector: "Hospitality",
    client_en: "Rixos Hotels",
    client_ar: "فنادق ريكسوس",
    location_en: "Baghdad, Iraq",
    location_ar: "بغداد، العراق",
    description_en: "Landmark hospitality development with shotcrete works for critical structural elements requiring high-performance materials.",
    description_ar: "مشروع ضيافة معلمي يتضمن أعمال الخرسانة المرشوشة للعناصر الإنشائية الحرجة.",
    products: ["EUNIFLOW 612i", "DCIS", "Microsilica"],
    image_url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=800&auto=format&fit=crop",
  },
  {
    slug: "al-burouj",
    country: "Iraq",
    countryCode: "IQ",
    title_en: "Al-Burouj Residential Complex",
    title_ar: "مجمع البروج السكني",
    subtitle: "Large-Scale Residential",
    sector: "High Rise",
    client_en: "Lafarge",
    client_ar: "لافارج",
    location_en: "Iraq",
    location_ar: "العراق",
    description_en: "Large-scale residential development requiring durable and reliable concrete solutions for long-term performance.",
    description_ar: "مشروع سكني واسع النطاق يتطلب حلول خرسانية متينة وموثوقة لأداء طويل الأمد.",
    products: ["Microsilica", "DCIS"],
    image_url: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=800&auto=format&fit=crop",
  },
  {
    slug: "abu-nuwas-bridge",
    country: "Iraq",
    countryCode: "IQ",
    title_en: "Abu Nuwas Street Bridge",
    title_ar: "جسر شارع أبو نواس",
    subtitle: "Transport Infrastructure",
    sector: "Infrastructure",
    client_en: "Taj Al-Sahel Company",
    client_ar: "شركة تاج الساحل",
    location_en: "Iraq",
    location_ar: "العراق",
    description_en: "Key transport infrastructure development supporting improved connectivity and traffic flow with durable construction solutions.",
    description_ar: "مشروع بنية تحتية رئيسي للنقل يدعم تحسين الاتصال وانسياب المرور من خلال حلول بناء متينة.",
    products: ["ECA Technology Products"],
    image_url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=800&auto=format&fit=crop",
  },
  {
    slug: "al-aziziyah-bridge",
    country: "Iraq",
    countryCode: "IQ",
    title_en: "Al-Aziziyah Concrete Bridge",
    title_ar: "جسر العزيزية الخرساني",
    subtitle: "Regional Infrastructure",
    sector: "Infrastructure",
    client_en: "Al-Buad Al-Rabea Company",
    client_ar: "شركة البعد الرابع",
    location_en: "Kut Governorate, Iraq",
    location_ar: "محافظة الكوت، العراق",
    description_en: "Important infrastructure development enhancing regional connectivity with high-performance concrete solutions.",
    description_ar: "تطوير مهم للبنية التحتية يعزز الربط الإقليمي بحلول خرسانية عالية الأداء.",
    products: ["EUNIFLOW 720C", "Microsilica"],
    image_url: "https://images.unsplash.com/photo-1587916823939-ce5c1c3d0d1e?q=80&w=800&auto=format&fit=crop",
  },
  {
    slug: "al-maamariyoon",
    country: "Iraq",
    countryCode: "IQ",
    title_en: "Al-Maamariyoon Towers Complex",
    title_ar: "مجمع أبراج المعماريون",
    subtitle: "Mixed-Use Development",
    sector: "High Rise",
    client_en: "Al-Maamariyoon Towers Company",
    client_ar: "شركة أبراج المعماريون",
    location_en: "Baghdad, Iraq",
    location_ar: "بغداد، العراق",
    description_en: "Prominent mixed-use development in Baghdad with comprehensive waterproofing and repair solutions.",
    description_ar: "مشروع بارز متعدد الاستخدامات في بغداد مع حلول شاملة للعزل المائي والإصلاح.",
    products: ["EUNICOTE 512W", "EURIPARE 502", "EUNISEAL PU Sealant", "EURIPARE BA9"],
    image_url: "https://images.unsplash.com/photo-1486718448742-163732cd1544?q=80&w=800&auto=format&fit=crop",
  },
  {
    slug: "iraq-mall",
    country: "Iraq",
    countryCode: "IQ",
    title_en: "Iraq Mall",
    title_ar: "مول العراق",
    subtitle: "Major Commercial Development",
    sector: "Commercial",
    client_en: "Jawhara Baghdad and Iraq Towers Company",
    client_ar: "شركة جوهرة بغداد وأبراج العراق",
    location_en: "Baghdad, Iraq",
    location_ar: "بغداد، العراق",
    description_en: "Major commercial development with high-performance superplasticizing admixture for enhanced concrete workability and strength.",
    description_ar: "مشروع تجاري رئيسي يستخدم إضافات ملدنة عالية الأداء لتعزيز قابلية التشغيل وقوة الخرسانة.",
    products: ["Euniflow 612i"],
    image_url: "https://images.unsplash.com/photo-1567958451986-2de427a4a0be?q=80&w=800&auto=format&fit=crop",
  },
  {
    slug: "al-batirah-overpass",
    country: "Iraq",
    countryCode: "IQ",
    title_en: "Al-Batirah Overpass",
    title_ar: "مجسر البتيرة",
    subtitle: "Traffic Infrastructure",
    sector: "Infrastructure",
    client_en: "Al-Izza General Contracting Ltd.",
    client_ar: "شركة العزة للمقاولات العامة",
    location_en: "Iraq",
    location_ar: "العراق",
    description_en: "Infrastructure development improving traffic flow and transportation efficiency with robust concrete works.",
    description_ar: "تطوير للبنية التحتية يحسن تدفق المرور وكفاءة النقل بأعمال خرسانية قوية.",
    products: ["EUNIFLOW 612i"],
    image_url: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?q=80&w=800&auto=format&fit=crop",
  },
];

const seedProjects = async () => {
  try {
    for (const data of projectsData) {
      // Create or update project
      await Project.upsert(data, {
        conflictFields: ['slug'] 
      });
    }
    console.log(`✅ Seeded ${projectsData.length} Projects.`);
  } catch (error) {
    console.error('❌ Error seeding Projects:', error);
  }
};

module.exports = seedProjects;
